config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create'

  get '/recipes/:id/next' => 'recipes#next'
  get '/your_recipes' => 'recipes#your_recipes'
  get '/search' => 'recipes#search'
  get 'recipes_find_newest' => 'recipes#find_newest'
  get 'recipes_find_quickest' => 'recipes#find_quickest'
	get 'recipes_most_ingredients' => 'recipes#most_ingredients'
	
  # get '/ajax_new' => 'comments#ajax_new'

  resources :users
  resources :ingredients

  resources :recipes do
    resources :comments, only: [:show, :index, :new, :edit, :create]
  end
  resources :comments, only: [:index, :show, :new, :edit, :update, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :user
	validates_presence_of :content
	validates_presence_of :title
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # def ajax_new
  #   @comment = Comment.new
	# 	# render partial: 'ajax_new', locals: {comment: @comment}
	# 	render :_ajax_new, layout: false
  # end

  def index
    @recipe = Recipe.find(params[:recipe_id])
    # @comments = Recipe.find(params[:recipe_id]).comments.all
    @comments = @recipe.comments
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @recipe.comments}
    end
  end
  #find comment based on recipe id
  def show
    @recipe = find_by_id(Recipe)
    if params[:recipe_id]
      @comment = Recipe.find(params[:recipe_id]).comments.find(params[:id])
    else
      @comment = find_by_id(Comment)
    end
  end

  #create a new comment if the recipe id exists and attach it to that recipe id
	def new
		
		
		
    # if params[:recipe_id] && !Recipe.exists?(params[:recipe_id])
    #   redirect_to recipes_path, alert: "Recipe not found."
    # else
		# @comment = Comment.new(recipe_id: params[:recipe_id])
		@comment = Comment.new(recipe_id: params[:recipe_id])
		
		#show me new page without layout
		render :_ajax_new, layout: false
    # end
  end
	
  #create a comment and attach it to the current user.
	def create
		@comment = Comment.new(comment_params)
		@comment.user_id =  current_user.id
		@comment.save
		render json: @comment
  end

  #find the comment by id and update
  def update
    @comment = find_by_id(Comment)
    @comment.update(comment_params)
    redirect_to recipe_path(@comment.recipe)
  end

  #find comment by id and by recipe id, if user who created it wants to edit, allow or prevent and redirect to recipe
  def edit
    @recipe = find_by_id(Recipe)
    @comment = find_by_id(Comment)
    if session[:user_id] != @comment.user_id 
      redirect_to recipe_path, alert: "Not your comment to edit."
    else
      @comment = find_by_id(Comment)
    end
  end

  #find comment by id, verify user created it before deleting, re-direct and prevent if not
  def destroy
    @recipe = find_by_id(Recipe)
    @comment = find_by_id(Comment)
    if session[:user_id] != @comment.user_id 
      redirect_to recipe_path, alert: "Not your comment to delete."
    else
      @comment = find_by_id(Comment)
      @comment.destroy!
      redirect_to user_path
    end
  end



  private

  #params for comments
  def comment_params
    params.require(:comment).permit(:user_id, :title, :content, :recipe_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def recipe_id_field(comment)
    if comment.recipe.nil?
    	binding.pry
      select_tag "comment[recipe_id]", options_from_collection_for_select(Recipe.all, :id, :title)
    else
      hidden_field_tag "comment[recipe_id]", comment.recipe_id
    end
  end
end

app/views/comments/_ajax_new.html.erb
 <%= form_for @comment, remote: true do |f| %>
 <p> ajax form ....</p>
 <label>Title:</label><br>
 <%= f.hidden_field :recipe_id %>
 <%= f.text_field :title %><br>
 <label>Comment </label><br>
 <%= f.text_area :content %><br>
 <%= f.submit %>
 <% end %>

app/views/comments/_form.html.erb
 <%= render 'users/show', user: @user %>
<h3><%= @comment.recipe.title %> </h3>
 <%= form_for(@comment) do |f| %>
 <label>Title:</label><br>
 <%= f.hidden_field :recipe_id %>
 <%= f.text_field :title %><br>
 <label>Comment </label><br>
 <%= f.text_area :content %><br>
 <%= f.submit %>
 <% end %>

app/views/comments/_form_errors.html.erb
<% if @comment.errors.any? %>
<div id="error_explanation">
	<h5><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h5>
	<ul>
		<% @comment.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/comments/_show.html.erb
<% if @comment != nil%>
<h5>Title: <%= @comment.title %></h5>
<h5>Content: <%= @comment.content%></h5>
<h5>By: <%= link_to @comment.user.name, user_path(@comment.user) %></h5>
<% if logged_in? && current_user%>
<%= link_to "Edit |", edit_recipe_comment_path(@comment.recipe_id, @comment)%>
<%= link_to "Delete", comment_path(@comment), :method => :delete %>
<%end%>
<%end%>

app/views/comments/edit.html.erb
<%= render partial: 'form' %>

app/views/comments/index.html.erb
<h5><strong>Comments <strong></h5>
<% @comments.each do |comment| %>
<h6> <i> Title: <%= comment.title %> <i></h6>
<h6>Content: <%= comment.content %></h6>
<h6>By: <%= comment.user.name %> </h6><br>
<% end %>

app/views/comments/new.html.erb
<%= render partial: 'form' %>
<%= render 'form_errors', form: @comment %>

app/views/comments/show.html.erb
<%= render partial: 'comments/show' %>