config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create'

  get '/recipes/:id/next' => 'recipes#next'
  get '/your_recipes' => 'recipes#your_recipes'
  get '/search' => 'recipes#search'
  get 'recipes_find_newest' => 'recipes#find_newest'
  get 'recipes_find_quickest' => 'recipes#find_quickest'
	get 'recipes_most_ingredients' => 'recipes#most_ingredients'
	
  # get '/ajax_new' => 'comments#ajax_new'

  resources :users
  resources :ingredients

  resources :recipes do
    resources :comments, only: [:show, :index, :new, :edit, :create]
  end
  resources :comments, only: [:index, :show, :new, :edit, :update, :destroy]
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
  has_many :comments
  has_many :recipe_ingredients
	has_many :ingredients, through: :recipe_ingredients
	
  validates :title, presence: true
  validates :category, presence: true
  validates :directions, presence: true
  validates :cook_time, presence: true

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank, allow_destroy: true

  scope :quickest, -> { order("cook_time ASC") }
  
  def self.valid_entry(params)
    return !params[:recipe][:title].empty? && !params[:recipe][:category].empty? && !params[:recipe][:directions].empty? && !params[:recipe][:cook_time].empty? 
  end

  def self.newest(total = all.size)
    order("ID DESC").limit(total)
  end

  def self.most_ingredients
    Recipe.select('recipes.*, count(ingredient_id) as ingredients_count').joins(:ingredients).group(:id).order('ingredients_count DESC')
  end
  

  def self.search(search)
    if !Ingredient.find_by(name: search)
      Recipe.none
    else
      ingredient = Ingredient.where("name LIKE ?", search)[0]
      @recipes = ingredient.recipes     
    end
  end

  def next
    recipe = Recipe.where("id > ?", id).first
    recipe ? recipe : Recipe.first
  end

  #deletes ingredients to avoid duplicating entire recipe when editing
  def delete_ingredients
      ingredients.size.times do
      ingredient = RecipeIngredient.find_by(recipe_id: self.id)
      ingredient.delete
    end
  end

  def add_ingredients(params)

    delete_ingredients
    
    params[:recipe_ingredients_attributes].each do |i, recipe_ingredient|

      if !recipe_ingredient[:ingredient][:name].empty?
        ingredient_name = recipe_ingredient[:ingredient][:name].downcase
        ingredient = Ingredient.find_or_create_by(name: ingredient_name)
      elsif !recipe_ingredient[:ingredient_id].empty?
        ingredient = Ingredient.find_by(id: recipe_ingredient[:ingredient_id])
      end

      if !recipe_ingredient[:amount].empty?
        RecipeIngredient.create(amount: recipe_ingredient[:amount], ingredient_id: ingredient.id, recipe_id: self.id )
      end
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :next]
  #find all recipes and current user
  def index
    @recipes = Recipe.all
    @user = current_user
    respond_to do |f|
      f.html
      f.json {render json: @recipes}
    end
  end

  def next
    if @recipe
      @next_recipe = @recipe.next
      render json: @next_recipe
    else
      redirect_to recipes_path
    end
  end

  #search method call from recipe model for search parameter
  def search
    @recipes = Recipe.search(params[:search])
  end

  #find recipe by id and display
  def show
    set_recipe
    # respond_to do |f|
    #   f.html {render :show}
    #   f.json {render json: @recipe}
    # end
  end


  #create new recipe and provide ingredient fields for existing and to create new
  def new
    @recipe = Recipe.new
    @ingredients = 10.times.collect { @recipe.recipe_ingredients.build }
  end

  #create recipe, associate to user, verify fields are complete and add ingredients to recipe before saving and redirect to show page for recipe
  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      @recipe.add_ingredients(recipe_ingredient_params)
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

#find recipe to edit, verify user who created it is trying to edit
  def edit
    @recipe = find_by_id(Recipe)
    if session[:user_id] == @recipe.user_id 
      recipe = 3.times.collect { @recipe.recipe_ingredients.build }
    else
      redirect_to recipes_path, notice: "That is not your recipe to edit!"
    end
  end

  #find recipe, add ingredients in ingredient params
  def update
    recipe = find_by_id(Recipe)
    if recipe.update(recipe_params)
      recipe.add_ingredients(recipe_ingredient_params)
      redirect_to recipe_path(recipe), notice: "Your recipe has successfully been updated"
    else  
      redirect_to new_recipe_path, alert: recipe.errors.full_messages.each {|m| m}.join
    end
  end

  #rediret if not users recipe, otherwise delete
  def destroy
    @recipe = find_by_id(Recipe)
    if session[:user_id] != @recipe.user_id 
      redirect_to recipe_path, alert: "Not your recipe to delete."
    else
      @recipe = find_by_id(Recipe)
      @recipe.destroy!
      redirect_to recipes_path
    end
  end

  #find newest recipe using AR with method in model
  def find_newest
    @recipes = Recipe.newest
    render "recipes/index"
  end

  #find newest recipe using AR with method in model
  def find_quickest
    @recipes = Recipe.quickest 
    render "recipes/index"
  end
  
  #order recipes from least to most ingredients using AR with method in model
  def most_ingredients
    @recipes = Recipe.most_ingredients
    render "recipes/index"
  end


  private

  #find recipe
  def set_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end

  #params for a recipe
  def recipe_params
    params.require(:recipe).permit(:title, :category, :directions, :cook_time, :search)
  end
  
  #params for adding ingredients
  def recipe_ingredient_params
    params.require(:recipe).permit(recipe_ingredients_attributes: [:amount, :ingredient_id, ingredient: [:name]])
  end
end

app/views/recipes/_ajax_new.html.erb
<div id= "ajax_form">

<h1>This is the ajax partial "ajax_new" in RECIPES views folder</h1>
<h3><%= comment.recipe.title %> </h3>
 <%= form_for comment, remote: true do |f| %>
 <label>Title:</label><br>
 <%= f.hidden_field :recipe_id %>
 <%= f.text_field :title %><br>
 <label>Comment </label><br>
 <%= f.text_area :content %><br>
 <%= f.submit %>
 <% end %>
</div>

app/views/recipes/_form.html.erb
  <h3> Recipe: </h3>
  <%=form_for @recipe do |f|%>

  <%=f.label :title, "Title"%><br>
  <%=f.text_field :title%><br>

  <%=f.label :category, "Category"%><br>
  <%=f.text_field :category%><br>

  <h3>Ingredients:</h3>

    <%= f.fields_for :recipe_ingredients, @ingredients do |recipe_ingredient| %>
      <%= recipe_ingredient.collection_select :ingredient_id, Ingredient.order('name ASC').all, :id, :name, include_blank: 'Select Ingredient' %>
      Amount: <%= recipe_ingredient.text_field :amount %>

      <%= recipe_ingredient.fields_for :ingredient, recipe.ingredients.build do |ingredient| %>
      -- Add new: <%= ingredient.text_field :name %><br>
      <% end %>
    <% end %>
  <%=f.label :directions, "Directions"%><br>
  <%=f.text_field :directions%><br>

  <%=f.label :cook_time, "Cook time (in minutes)"%><br>
  <%=f.number_field :cook_time%><br>

  <%=f.submit%>
  <%end%>
    <%= render 'layouts/form_errors', form: @recipe %>

app/views/recipes/edit.html.erb
 <h3>Update Recipe</h3>
<%= render 'form', recipe: @recipe, ingredient: @recipe.recipe_ingredients %>
  
     

app/views/recipes/index.html.erb
 <%if logged_in? %>
 <%= render 'users/show', user: @user %>


 

 
<h3>All Recipes</h3>
 <% @recipes.each do |recipe|%>
 <%=link_to recipe.title, recipe_path(recipe), class: "recipes"%> <br>
 <%end%>
 <% else %>
  <%= render template: 'users/welcome' %>
 <%end%>

app/views/recipes/new.html.erb
 <%= render 'users/show', user: @user %>

<%= render 'recipes/form', recipe: @recipe, ingredient: @ingredients %>

app/views/recipes/search.html.erb
 <h4>Search by Ingredient:</h4>
 <%= form_tag(search_path, method: :get) do %>
 <%= text_field_tag :search, params[:search]%>
 <%= submit_tag 'Search', name: nil %>
 <% end %>




 <h3>Recipes</h3>
 <% @recipes.each do |recipe|%>
 <%=link_to recipe.title, recipe_path(recipe)%> <br>
 <%end%>

app/views/recipes/show.html.erb
<% if !@recipe.nil? %>
<h4><%="#{@recipe.title}"%></h4>
<h6>Created By: <%="#{@recipe.user.name}"%></h6>
<h5>Category-  <%="#{@recipe.category}"%></h5>
<%= render 'ingredients/show_ingredients', recipe: @recipe %>
<h5>Directions-  <%="#{@recipe.directions}"%></h5> 
<h5>Cook Time-  <%="#{@recipe.cook_time}"%> minutes </h5> 
<%= link_to "All Comments |", recipe_comments_path(@recipe), class: "all_comments" %>

<%= link_to  "New Comment |", new_recipe_comment_path(@recipe), class: "new_comment", remote: true%>
<%if logged_in? %>
<%=link_to "Edit |", edit_recipe_path(@recipe)%>
<%=link_to "Delete", recipe_path(@recipe), :method => :delete%>
<%end%>

<div id="new_comment_response">++++++++++++++++</div>


<div id= "comment_form"></div>
<h5>Comments: <br>
 <% @recipe.comments.each do |comment| %>
  <div><%= link_to comment.title, recipe_comment_path(@recipe, comment), class: "comment_list" %></div>
<% end %>
</h5>
<%end%>

app/views/recipes/your_recipes.html.erb
<%if logged_in? %>
 <%= render 'users/show', user: @user %>

<h3>Your Recipes</h3>
 <% current_user.recipes.each do |recipe|%>
 <%=link_to recipe.title, recipe_path(recipe)%> <br>
 <%end%>
 <% else %>
  <%= render template: 'users/welcome' %>
 <%end%>