config/routes.rb
Rails.application.routes.draw do

  root 'users#welcome'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get 'auth/:provider/callback' => 'sessions#create'

  get '/recipes/:id/next' => 'recipes#next'
  get '/your_recipes' => 'recipes#your_recipes'
  get '/search' => 'recipes#search'
  get 'recipes_find_newest' => 'recipes#find_newest'
  get 'recipes_find_quickest' => 'recipes#find_quickest'
	get 'recipes_most_ingredients' => 'recipes#most_ingredients'
	
  # get '/ajax_new' => 'comments#ajax_new'

  resources :users
  resources :ingredients

  resources :recipes do
    resources :comments, only: [:show, :index, :new, :edit, :create]
  end
  resources :comments, only: [:index, :show, :new, :edit, :update, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :recipes
	has_many :comments
	has_many :ingredients, through: :recipes
	validates :name, presence: true
	validates :name, uniqueness: true
	validates :password_digest, :presence => true, 
			    :unless => :has_password?

	def has_password?
		!self.password_digest.blank?
	end
	

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.name = auth.info.name
			user.oauth_token = auth.credentials.token
			user.oauth_expires_at = Time.at(auth.credentials.expires_at)
			user.password = SecureRandom.urlsafe_base64
			user.save!
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #new instantiates a new ActiveRecord model without saving it to the database  def new
  def new
    @user = User.new
  end

  #create immediately attempts to save it, as if you had called #new and then #save.
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
    respond_to do |f|
      f.html
      f.json {render json: @user}
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

  
end

app/views/users/_form.html.erb
<%=f.label :name%><br>
<%=f.text_field :name%><br>
<%=f.label :password%><br>
<%=f.text_field :password%><br>

app/views/users/_show.html.erb
<%=link_to "| Add Recipe |", new_recipe_path%>
 <%= link_to "Newest |", recipes_find_newest_path%>
 <%= link_to "Quickest cook time |", recipes_find_quickest_path%>
 <%= link_to "Search |", search_path%>
 <%= link_to "Ingredient count |", recipes_most_ingredients_path%>
 <%= link_to "Your Recipes |", your_recipes_path, class: "your_recipes"%>
 <%= link_to "All Recipes |", recipes_path, class: "recipes"%>
 <%= link_to "Sign out |", logout_path, method: :delete %><br><br>

app/views/users/new.html.erb
<h2>SignUp:</h2>

<%= form_for @user do |f| %>
  <%= render 'form', f: f %>

<%=f.submit "Create User"%>
<%end%>
<%=link_to("Login ", login_path)%><br>

<%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>

app/views/users/show.html.erb
 <%= render 'users/show', user: @user , remote: true %>

app/views/users/welcome.html.erb
Welcome!</br>
<%=link_to("Sign-Up |", new_user_path)%>
<%=link_to("Login ", login_path)%><br>